# Generated by Django 4.1.7 on 2023-04-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saatja', models.CharField(max_length=150)),
                ('saaja', models.CharField(max_length=150)),
                ('summa', models.FloatField()),
                ('dt', models.DateTimeField(verbose_name='date sent')),
            ],
        ),
    ]
